services:
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: "socialnetworkDb"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "admin"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        command: redis-server --requirepass redis_admin
volumes:
    postgres-data:
    redis-data: